export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
export const SET_ITEM_LIST = 'SET_ITEM_LIST';
export const APPEND_ITEMS_TO_LIST = 'APPEND_ITEMS_TO_LIST';
export const SET_WIDGET_PAGE = 'SET_WIDGET_PAGE';
export const INCREMENT_WIDGET_PAGE = 'INCREMENT_WIDGET_PAGE';
export const SWITCH_WIDGET_LAZY = 'SWITCH_WIDGET_LAZY';

export const UPDATE_CART_POSITION_COUNTER = 'UPDATE_CART_POSITION_COUNTER';